### ISSUE TITLE
values are not saved in. csv

### ISSUE THREAD

**Issue by ZvonimirKucis** [marshq/europilot#10]
Hy,  i have tried running europilot,  and in. csv file pictures were saved but al other values were 0.
when i run joystick. py the output whas UNKNOWN: b'200': some number. 

I fixed that,  and now it sayd wheel-axis some_number. But it doesnt save the value in. csv

**Comment by daftshady** [comment]
How did you fix that `UNKNOWN` output? Did you modify europilot source code?

**Comment by ZvonimirKucis** [comment]
![mjennaj](https://user-images.githubusercontent.com/22710386/32698207-c2db3e62-c7a1-11e7-9a94-6586d677dc4f.png)

I marked on picture things i have changed.
