### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by Alexr03** [marshq/europilot#11]
I don't know about anyone else but I would LOVE a windows version of this since it's my usual OS. Works flawlessly on my virtual machine. I understand Windows support is on your roadmap, but I believe it would be great to get this out to Windows users to use! Cheers.

**Comment by M0RG4N01** [comment]
I agree with @Alexr03! 😉 😜  I would LOVE a windows support to come to this amazing add-on to ETS 2. I would love to bug test participate in any bug testing for windows versions of this add-on (if you require any bug testers). Thank you in advanced! +1 😄

**Comment by SUNDREAM2018** [comment]
I agree to the with the ETS2 simsuation conunsiil the system preparing the assicocated.

**Comment by daftshady** [comment]
https://github.com/marsauto/europilot/issues/15
