### ISSUE TITLE
"Getting Started" should explain how to get started

### ISSUE THREAD

**Issue by erikbsap** [marshq/europilot#12]
You know... Let's say I've downloaded ETS2 via Steam and pip installed europilot. Now what? How do I get to what you show in the gif? Do I need to configure something? Do I need to run my own training before I can use it?

**Comment by Raoulgold** [comment]
I have the same issue here. I don't know what should i run and in which order.

**Comment by daftshady** [comment]
Please read the `Getting started` section of a README more carefully. Also, check out https://github.com/marsauto/europilot/tree/master/scripts for detailed step-by-step explanation. If you guys understand how end-to-end control system works (See https://arxiv.org/abs/1604.07316), i think the README itself is more than enough.
