### ISSUE TITLE
is it possible to using [mouse+keyboard] instead of using [Logitech G27] ?

### ISSUE THREAD

**Issue by wooheaven** [marshq/europilot#14]
Thanks to you,
I can follow everything of europilot except the joystick [Logitech G27].
Even though this problem, I think that this repository is good change to me.

As mentioned in General Architecture on README.md ,
" If you have a different joystick, modify joystick.py to your needs. "

is it possible to using [mouse+keyboard] instead of using [Logitech G27] ?
Because it's hard to buy the joystick [Logitech G27] for me.

I guess that you have experienced about this joystick
Can you any guide or answer to me about [mouse+keyboard] alternatives ?

If I know the alternatives and implemented, then I will PR on this repository.

----In Korean----

제가 영어가 짧아서 위에 간략하게 적었습니다.
한글로 적어 보겠습니다.

여기 저장소 덕분에 
europilot 을 알게 되었고, joystick 에서 문제를 만났지만 좋은 도전이 될 것 같다는 생각에는 변함이 없습니다. 

README.md 에서도 언급했지만
[Logitech G27]을 사용할 수 없다면 직접 joystick.py를 수정하라고 명시되어 있습니다.

제가 [Logitech G27]을 구입하려했지만 
비싸서 대안으로 [mouse+keyboard]로 사용가능한지 문의드립니다.

제 추측으로는 여기에서 구현한 joystick 을 만들면서 충분히 고민하고 경험을 했을것 같습니다.
[mouse+keyboard]에 대한 참고할만한 가이드 또는 볼만한 링크라도 알고 계시면 답변 부탁드립니다.

만일 제가 대안을 알게 되고, 구현 한다면 여기에 PR 올리도록 하겠습니다.

**Comment by ghost** [comment]
26 day pending?

**Comment by sschertler** [comment]
It's a bit late now but if you're still interested [https://github.com/Sentdex/pygta5/](url) is a place to start. It plays with the idea to use the Keyboard + OpenCV and the InceptionV3 Model from Google.

You can find an overview on **https://psyber.io** or videos about the project on **https://youtube.com/sentdex**

He is using GTA 5 as an example but other games are also possible

**Comment by daftshady** [comment]
Sorry for the late reply. We don't have a time to develop the keyboard support right now. However, implementing it would be quite straightforward. Pull requests are always welcomed.
