### ISSUE TITLE
Balancing raw data

### ISSUE THREAD

**Issue by sschertler** [marshq/europilot#16]
Is there any need to undersample data which is available more often than other? (It‘s likely to get more data driving with a steering angle close to 0). Wouldn‘t the trained network go simply straight because of the data? But the only thing I found was the notebook which calculated the mean and std.

Is that enough?
I would be happy for any explanation!

**Comment by daftshady** [comment]
If you train your model properly, exiting data should be enough to drive like a youtube video in README.
