### ISSUE TITLE
Virtual controller setup

### ISSUE THREAD

**Issue by vadbut** [marshq/europilot#17]
Hi,

I was wondering what the following sentence mean?
"Please note that the driver must be initialized before the game is started, or else it will not show up in the controller page."

Does it mean that the G27 has to be plugged in so it shows up in the devices?
If yes, is there a way to initialize the driver without actually having G27 ?

**Comment by daftshady** [comment]
Yes, it means that G27 has to be plugged and loaded before the game is started.
Right now, you need to have a G27 to use europilot. But you can use your own controller if you have one by implementing your own `joystick.py`.
