### ISSUE TITLE
car 

### ISSUE THREAD

**Issue by Learningbug04** [marshq/europilot#3]
I was interested in the Euro Pilot. But I have some questions. In a video, a car follows a lane perfectly. But does the car stop when it is red? I would like to ask if it is possible to adjust the distance of the front car. Finally, I wonder if car can reach its destination!

**Comment by oliver-im** [comment]
Hey swha03, thanks for the interest.

Right now our implementation is based on [End to End Learning for Self-Driving Cars](https://arxiv.org/abs/1604.07316), which takes as input the front image and outputs the steering angle. Therefore while the model can control the car to follow the lane, it does not issue commands for stopping at the red light, nor does it adjust the speed relative to the distance to the front car.

Pull requests are welcome :)
