### ISSUE TITLE
Unable to use keyboard for generating training data

### ISSUE THREAD

**Issue by thanif** [marshq/europilot#4]
I am unable to generate data using keyboard instead of joystick. What are the steps to be followed for using the code with a keyboard. Is the training data publicly available or will be made available in future.

**Comment by Vilour** [comment]
I have the same issue. Actually, to test an algorithm, we don`t need to deal with so much data.The accelerating and steering are enough.

**Comment by oliver-im** [comment]
RIght now keyboard events are not supported, but it shouldn't be too difficult to add them. I'll try to upload the some training data as well. I'll ping you when it's done!

**Comment by thanif** [comment]
Thank You

**Comment by iceacman** [comment]
also interested in whether we can have keybord support，thanks°。°

**Comment by oliver-im** [comment]
Hey everyone,

In the README I added a link for a dataset consisting of 162,495 images.
You can download it [here](https://drive.google.com/file/d/0B42sVbnSOCJ4bnZhWF80b0xUY28/view?usp=sharing).

**Comment by aryarohit07** [comment]
Thanks for this project and dataset.
I downloaded the dataset, but the `csv` is only having **image -> wheel-axis** and not other labels like brake, gas, etc.
