### ISSUE TITLE
How to control ETS2 and emulate steering wheel in Windows? 

### ISSUE THREAD

**Issue by Theru1** [marshq/europilot#6]
Hi all! How to control ETS2 and emulate steering wheel in Windows?

**Comment by daftshady** [comment]
Windows is not supported yet. But it's on our roadmap and i feel like i should work on it sooner or later.

**Comment by silverstone1903** [comment]
Hi!

Can I install it on Windows 10 with subsystem for Linux? Is it possible to do that?
