### ISSUE TITLE
where is 'v5-PilotNet_v2-009-0.67221.h5' file?

### ISSUE THREAD

**Issue by Alpslee** [marshq/europilot#7]
I run inference.ipynbls, an error occurred:

%ls $model_path
/Users/Rand/europilot/model: No such file or directory

**Comment by oliver-im** [comment]
Hey Alpslee,

As of now pretrained models are not uploaded. But I just added a dataset of 17G, which you can download [here](https://drive.google.com/file/d/0B42sVbnSOCJ4bnZhWF80b0xUY28/view?usp=sharing).

**Comment by Alpslee** [comment]
Appreciate it!

2017年10月9日 下午6:18，"Gyuri Im" <notifications@github.com>写道：
