### ISSUE TITLE
Modifying underlying CNN

### ISSUE THREAD

**Issue by apclypsr** [marshq/europilot#8]
Hi,

I am wondering if it is possible to modify the underlying CNN with a different CNN structure (say, adding more filters) and rebuild the package myself to achieve different results from the same training data. Let me know if this is feasible.

Thanks,
Lou

**Comment by oliver-im** [comment]
Hi apclypsr,

The project is agnostic of which framework or architecture you use, so it is definitely possible. The model defined in the scripts folder is more intended to be an example rather than a definitive way of doing things.
