### ISSUE TITLE
ETS2 Game EULA

### ISSUE THREAD

**Issue by IbrahimSobh** [marshq/europilot#9]
Dear

Thank you for the great work!

**You mentioned that:**

> "With europilot, you can capture the game screen input, and programmatically control the truck inside the simulator."

Is it allowed by the ETS2 EULA? 

Best Regards

**Comment by daftshady** [comment]
I don't know about specific terms in ETS2 EULA, but I think europilot is nothing to do with it as it doesn't modify or inject something to the game. It captures game screen outside of game and put a key input by creating virtual joystick in OS. So, it doesn't depend on specific game and ETS2 is just one of possible applications.
